name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: ["chrome", "firefox"]

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up Deno
      uses: denolib/setup-deno@v2

    - name: build
      run: |
        deno run --allow-all --unstable build.ts

    - name: Test
      run: |
        deno run --allow-all --unstable test.ts

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Deno
      uses: denolib/setup-deno@v2

    - name: Format
      run: |
        deno fmt --check

    - name: Lint
      run: |
        deno lint --unstable
