name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: ["chrome", "firefox"]

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up Deno
      uses: denolib/setup-deno@v2
      with:
        deno-version: 1.4.0

    - name: Build
      run: |
        deno run --allow-all --unstable build.ts

    - name: Run tests
      run: |
        deno run --allow-all --unstable test.ts

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Deno
      uses: denolib/setup-deno@v2
      with:
        deno-version: 1.4.0

    - name: Lint
      run: |
        deno lint --unstable

    - name: Check format
      run: |
        deno fmt --check
