name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up
      uses: denolib/setup-deno@v2

    - name: build
      run: |
        deno run --allow-all --unstable build.ts
